---

- name: Create ServiceNow incident ticket
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create incident
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        type: standard
        requested_by: splunk_ansible_workflow
        short_description: Block IP Workflow
        description: Splunk AAP workflow blocking IP - ticket review
        priority: moderate
        impact: low
        risk: low
        other:
          expected_start: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
      register: change_out

    - name: Set change Number
      ansible.builtin.set_stats:
        data:
          ServiceNow_Change_Number: "{{ change_out.record.number }}"
