---
- name: Decide whether approval is required to block IP
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/bad_countries.yml

  tasks:
    - name: debug bad_decisions
      ansible.builtin.debug:
        var: bad_countries
      tags: 
        - 'never'
        - 'debug'
   
    - name: debug location_data innards
      ansible.builtin.debug:
        var: item.value
      loop: "{{ query('ansible.builtin.dict', location_data) }}"
      tags: 
        - 'never'
        - 'debug'

    - name: fail when the ip geolocation isn't in a bad country (allows workflow to continue without hotl)
      ansible.builtin.set_fact:
        location: item.value
      loop: "{{ query('ansible.builtin.dict', location_data) }}"
      failed_when: "item.value not in bad_countries "
