---
- name: Create an incident ticket in ServiceNow
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create incident
      tags:
        - create_incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: truch
        short_description: "Service Availability issue: {{ problem_id | default('Problem ID') }}"
        description: >
          "{{ ansible_eda.event.payload.eventData | to_nice_json }}"
        impact: med
        urgency: med
        other:
          expected_start: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
      register: incident_out

    - name: Close incident
      when: incident_state == 'closed'
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: closed
        number: "{{ incident_out.record.number }}"
        close_code: "Solved (Permanently)"
        close_notes: "Ansible workflow resolved incident and Dyntrace marked problem as closed"

    - name: Set Incident Number
      ansible.builtin.set_stats:
        data:
          ServiceNow_Incident_Number: "{{ incident_out.record.number }}"

