---
- name: Create an incident ticket in ServiceNow
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create incident
      servicenow.itsm.incident:
        instance:
          host: "{{ lookup('env','SN_HOST') | default(omit) }}"
          # api_key: "{{ lookup('env','SN_API_KEY') | default(omit) }}"
          username: "{{ lookup('env','SN_USERNAME') | default(omit) }}"
          password: "{{ lookup('env','SN_PASSWORD') | default(omit) }}"
        state: new
        caller: truch
        short_description: "Service Availability issue: {{ problem_id | default('Problem ID') }}"
        description: >
          "Just some rando data here, not sure what to put in here, but it should be something useful."

        # "{{ ansible_eda.event.payload.eventData | to_nice_json | default('No event data provided') }}"
        impact: med
        urgency: med
        other:
          expected_start: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
      register: incident_out

    - name: Close incident
      when: incident_state == 'closed'
      servicenow.itsm.incident:
        instance:
          host: "{{ lookup('env','SN_HOST') | default(omit) }}"
          # api_key: "{{ lookup('env','SN_API_KEY') | default(omit) }}"
          username: "{{ lookup('env','SN_USERNAME') | default(omit) }}"
          password: "{{ lookup('env','SN_PASSWORD') | default(omit) }}"
        state: closed
        number: "{{ incident_out.record.number }}"
        close_code: "Solved (Permanently)"
        close_notes: "Ansible workflow resolved incident and Dyntrace marked problem as closed"

    - name: Set Incident Number
      ansible.builtin.set_stats:
        data:
          ServiceNow_Incident_Number: "{{ incident_out.record.number }}"

