---
- name: Create an incident ticket in ServiceNow
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: new
        caller: splunk_ansible_workflow
        short_description: Incident from ITSM Incident AI Flow
        description: "{{ slack_message | default('No description provided') }}\n{{ rca_prompt | default('No RCA provided') }}"
        impact: med
        urgency: med
        other:
          expected_start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      register: incident_out

    - name: Set Incident Number
      ansible.builtin.set_stats:
        data:
          ServiceNow_Incident_Number: "{{ incident_out.record.number }}"

...
