---

- name: Create ServiceNow incident ticket
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Debugging statement
      ansible.builtin.debug:
        msg: Running ServiceNow Updates

    - name: Retrieve change requests by number
      tags:
        - info
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
      register: result

    - name: Debug change number
      ansible.builtin.debug:
        msg: "{{ result }}"
        verbosity: 2
      when: result is defined

    - name: Mark change request as implement
      tags:
        - implement
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: implement
      register: change

    - name: Mark change request as review
      tags:
        - review
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: review
      register: change

    - name: Mark change request as Closed
      tags:
        - closed
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: closed
        close_code: "{{ close_code | default('successful') }}"
        close_notes: "{{ close_notes | default('Everything was completed') }}"
      register: change

    - name: Find a ServiceNow Record
      tags:
        - find_record
      servicenow.servicenow.snow_record_find:
        table: sc_request
        query:
          number: "{{ change_number }}"
      register: Record

    - name: Debugging statement
      tags:
        - find_record
      ansible.builtin.debug:
        msg: "{{ Record }}"
      when: Record is defined

    - name: Close ServiceNow Request
      tags:
        - close_request
      servicenow.servicenow.snow_record:
        table: sc_request
        number: "{{ change_number }}"  # Replace with the actual request ID
        request_state: "Closed Complete"  # Or the appropriate closed state value
        state: present

...
