---

- name: Create ServiceNow incident ticket
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Mark change request as authorize
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: authorize
        on_hold: false
        assignment_group: 'Change Management'
        other:
          planned_start: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
          answer: true
      register: change
 
    - name: Mark change request as scheduled
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: scheduled
        assignment_group: 'Change Management'
        on_hold: false
      register: change

    - name: Mark change request as implement
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: implement
        #assignment_group: 'Change Management'
      register: change

    - name: Mark change request as review
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: review
        assignment_group: 'Change Management'
      register: change

    #- name: Set fact for change number
    #  ansible.builtin.set_fact:
    #    change_number: "{{ change_out.record.number }}"

 

