---

- name: Create ServiceNow incident ticket
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Debugging statement
      ansible.builtin.debug:
        msg: Running ServiceNow Updates

    - name: Retrieve change requests by number
      tags:
        - info
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
      register: result

    - name: Debug change number
      debug:
        msg: "{{ result }}"

    - name: Mark change request as implement
      tags:
        - implement
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: implement
      register: change

    - name: Mark change request as review
      tags:
        - review
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: review
      register: change

    - name: Mark change request as Closed
      tags:
        - closed
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: closed
        close_code: "{{ close_code | default('successful') }}"
        close_notes: "{{ close_notes | default('Everything was completed') }}"
      register: change
 

