---

- name: Create ServiceNow incident ticket
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Debugging statement
      ansible.builtin.debug:
        msg: Running ServiceNow Updates

    - name: Mark change request as implement
      tags:
        - implement
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: implement
      register: change

    - name: Mark change request as review
      tags:
        - review
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: review
      register: change

    - name: Mark change request as Closed
      tags:
        - closed
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: closed
        close_code: "{{ close_code }}"
        close_notes: "{{ close_notes }}"
      register: change
 

