---

- name: ServiceNow Change Request Tasks
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create Change Request Ticket in ITSM System
      tags:
        - create
      block:
        - name: Create Change Request
          servicenow.itsm.change_request:
            instance:
              host: "{{ SN_HOST }}"
              username: "{{ SN_USERNAME }}"
              password: "{{ SN_PASSWORD }}"
            state: new
            type: normal
            requested_by: "splunk_ansible_workflow"
            description: |
              '{{ inventory_hostname }} is out of compliance.
              Use the following URL for details: {{ job_url }}'
            short_description: "{{ inventory_hostname }}"
            priority: low
            impact: low
            risk: low
            urgency: medium
            category: network
            assignment_group: 'Network CAB Managers'
            other:
              start_date: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
              expected_start: "{{ lookup('pipe','date +%Y%m%d%H%M%S')}}"
              implementation_plan: >
                Implement the following playbook, which will run the tasks detailed in the second link
                https://student1.pnbzp.example.opentlc.com/#/templates/job_template/24/details
                https://gitlab.com/redhatautomation/network_demos/-/blob/main/base_configuration/network_STIG_set.yml?ref_type=heads
              answer: true
          register: change_out
          delegate_to: localhost

        - name: Set fact for change number
          ansible.builtin.set_fact:
            #change_number: 'CHG0030022'
            change_number: "{{ change_out.record.number }}"
        
        - name: Debug change number
          ansible.builtin.debug:
            msg: "{{ change_number }}"
      check_mode: false

    - name: Retrieve change requests by number
      tags:
        - info
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
      register: result

    - name: Debug change number
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Mark change request as implement
      tags:
        - implement
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: implement
      register: change

    - name: Mark change request as review
      tags:
        - review
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: review
      register: change

    - name: Mark change request as Closed
      tags:
        - closed
      servicenow.itsm.change_request:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ change_number }}"
        state: closed
        close_code: "{{ close_code | default('successful') }}"
        close_notes: "{{ close_notes }}"
      register: change
 


    # - name: Set change Number
    #   ansible.builtin.set_stats:
    #     data:
    #       change_number: "{{ change_number }}"