---
- name: Update ServiceNow record
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Close ServiceNow Request
      servicenow.itsm.api:
        resource: sc_request
        action: post
        # table: sc_request
        number: "{{ change_number }}"  # Replace with the actual request ID
        data:
          request_state: "Closed Complete"  # Or the appropriate closed state value
      register: request_update

    - name: Debug ServiceNow Request Update
      debug:
        var: request_update
        verbosity: 2
      when: request_update is defined and request_update.status == 200
