- name: Block IP in Palo Firewall
  hosts: all
  connection: local
  gather_facts: False
 
  collections:
    - paloaltonetworks.panos



#  vars:
#    device:
#      ip_address: '{{ ip_address }}'
#      username: '{{ username | default(omit) }}'
#      password: '{{ password | default(omit) }}'
#      api_key: '{{ api_key | default(omit) }}'

  tasks:
    - name: print provider
      ansible.builtin.debug:
        var: provider

    - name: Update security rule Block Web
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'Block Web'
        source_zone: ['Untrust']
        destination_zone: ['Web']
        source_ip: '{{ splunk_host_list }}'
        #source_ip: ['71.244.221.4', '71.244.221.3']
        destination_ip: ['any']
        application: ['any']
        service: ['service-http']
        action: 'deny'
        state: 'merged'
        #tag_name: ['Prod']
        commit: False

    - name: Commit candidate config on firewall
      paloaltonetworks.panos.panos_commit:
        provider: '{{ provider }}'
