- name: Block IP in Palo Firewall
  hosts: all
  connection: local
  gather_facts: False
 
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Update security rule Block Web
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ provider }}'
        rule_name: 'Block Host'
        source_zone: ['Untrust']
        destination_zone: ['Web']
        source_ip: '{{ block_ip }}'
        #source_ip: ['71.244.221.4', '71.244.221.3']
        destination_ip: ['any']
        application: ['any']
        service: ['any']
        #service: ['service-http']
        action: 'deny'
        state: 'merged'
        #tag_name: ['Prod']
        commit: False

    - name: Commit candidate config on firewall
      paloaltonetworks.panos.panos_commit_firewall:
        provider: '{{ provider }}'
