---
- name: Poll ServiceNow for New Incidents
  hosts: all
  sources:
    - servicenow.itsm.records:
        table: incident
        # A basic query to look for new/active incidents.
        # The plugin will poll based on this query.
        interval: 20 # Polling interval in seconds
        sysparm_query: "active=true^state=1"
        remote_servicenow_timezone: "US/Eastern"

  rules:
    - name: Initial debug action
      condition: event.sys_id is defined
      action:
        run_job_template:
          name: "EDA ServiceNow Update"
          organization: Default
          job_args:
            extra_vars:
              message: From EDA ServiceNow source
              req_sys_id: "{{ event.sys_id }}"
              req_number: "{{ event.number }}"


    - name: Match all new incidents
      # The plugin returns the ServiceNow record under the 'record' key.
      # This condition simply ensures a record was returned.
      condition: event.record is defined
      action:
        print_event:
          pretty: true



...
