---
- name: Retrieve data about objects from the firewall
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks:
 
  - name: Retrieve service group object 'Prod-Services'
    ansible.builtin.debug:
      var: item
    loop: "{{ hosts }}"
