download_url: https://galaxy.ansible.com/download/paloaltonetworks-panos-2.16.0.tar.gz
format_version: 1.0.0
name: panos
namespace: paloaltonetworks
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.16.0
version_url: https://galaxy.ansible.com/api/v2/collections/paloaltonetworks/panos/versions/2.16.0/
