download_url: https://galaxy.ansible.com/download/containers-podman-1.10.1.tar.gz
format_version: 1.0.0
name: podman
namespace: containers
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.10.1
version_url: https://galaxy.ansible.com/api/v2/collections/containers/podman/versions/1.10.1/
